### ISSUE TITLE
Content

### ISSUE THREAD

**Issue by jriwanek** [MinecraftModDevelopmentMods/ModernMetals#1]
https://github.com/MinecraftModDevelopmentMods/BaseMetals/issues/61

**Comment by Divineaspect** [comment]
Reinforcement Table/Workbench: This takes tools and adds special properties to a tool which doesn't already have them, based on the material property of the rod used in it's augmentation. This presumes it's non feasible to just make rods usable in place of sticks for tools for the same effect.

**Comment by jriwanek** [comment]
Updated for new content progress

**Comment by jriwanek** [comment]
Moved to:
https://github.com/MinecraftModDevelopment/BaseMetals/issues/61

A Reinforcement Table or workbench is beyond the scope of this mod.
