### ISSUE TITLE
TiCon tools made of Modern Metals are not repairable in tool station

### ISSUE THREAD

**Issue by knoxhack** [MinecraftModDevelopmentMods/ModernMetals#102]
https://github.com/knoxhack/MMD-Dev-Server-Modpack/issues/10

**Comment by knoxhack** [comment]
Pickaxe made out of Iron: https://puu.sh/A31vO/5eb76e7ac0.png
Pickaxe made out of Boron: https://puu.sh/A31w0/fc2d8d8626.png

Tools are still repairable if you use a sharpening kit.

**Comment by dshadowwolf** [comment]
TiCon integration in ModernMetals is known to be buggy and is probably tied to the unholy mess that the system is, ATM

**Comment by YaibaToKen** [comment]
Should probably close this as it no longer seems to be an issue, at least as of the 17th of October of 2018, using the latest versions available at this point, on CurseForge.

![image](https://user-images.githubusercontent.com/9133736/47118052-0bb57400-d25e-11e8-92a7-74c50a32d458.png)
