### ISSUE TITLE
[1.12.2] Unobtainable metals

### ISSUE THREAD

**Issue by YaibaToKen** [MinecraftModDevelopmentMods/ModernMetals#107]
Stainless Steel and Nichrome seem to be unobtainable with mod versions:
BaseMetals-1.12-2.5.0-beta5.214;
ModernMetals-1.12-2.5.0-beta5.120
OreSpawn-1.12-3.3.0.136

**Comment by dshadowwolf** [comment]
I will have to look at the recipe json files - we've had some issues with the transition to them before

**Comment by YaibaToKen** [comment]
No problem :)

**Comment by zagal109** [comment]
'chromium' in recipe of Stainless Steel and Nichrome blend is named 'chrome'.

**Comment by dshadowwolf** [comment]
Yep. Thought I'd... oh, wait - there was a variation on this asked on the CF page that I answered and forgot about this one. Damn. Yes - Stainless Steel is a 1:1 of chrome and steel, nichrome is a 1:1 of nickel and chrome (if I'm remembering correctly)

**Comment by zagal109** [comment]
yes, and other chromium recipe is named chromium...
![image](https://user-images.githubusercontent.com/40393465/41601480-8fe6c8ea-7413-11e8-8a63-0e5554814acb.png)

![image](https://user-images.githubusercontent.com/40393465/41601539-b028e4d0-7413-11e8-8b9d-52b8e534f2c7.png)

**Comment by YaibaToKen** [comment]
Welp, they weren't showing up in JEI, though I haven't checked if they do on the newest version :9 feel free to close this if they do show up properly :)

**Comment by dshadowwolf** [comment]
Yep. Chrome is a generic, common name for the material, the actual, scientific name (as seen on an English version of the "Periodic Table of the Elements") is Chromium

**Comment by dshadowwolf** [comment]
I actually haven't tested myself as none of the packs I use for testing require them... And I've found that the fastest way to locate errors is to have "real world" tests where various bits are turned off or modified in the configs

**Comment by YaibaToKen** [comment]
Atm I'm only using the mod to test how well my own can integrate metals with Construct's Armory's system, and that environment is indeed using the latest versions, I can give it a spin and see if all of the metals seem obtainable.

**Comment by YaibaToKen** [comment]
ok, so using OreSpawn-1.12-3.3.0.136, BaseMetals-1.12-2.5.0-beta5.214 and ModernMetals-1.12-2.5.0-beta5.120, on a fresh world, with jei_1.12.2-4.10.0.198 I still can't see the recipes, though perhaps it just isn't registering them with JEI, I'll give it another look soon.

**Comment by dshadowwolf** [comment]
I have a feeling its actually an issue with the "conditions" block of the recipe JSONs - I auto-generated nearly all of them and don't know if I properly audited the source data - we've had issues with them in the past, as well

**Comment by YaibaToKen** [comment]
@dshadowwolf closing this as I just decided to test the new versions today and the recipes are indeed the ones you pointed :)
