### ISSUE TITLE
[1.12.2] Crash on startup

### ISSUE THREAD

**Issue by ghost** [MinecraftModDevelopmentMods/ModernMetals#108]
I have repeatedly tried to use this mod, but this keeps happening:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  BIFLoader (Bow-Infinity-Fix-Mod-1.12.2.jar)
  ObfuscatePlugin (obfuscate-0.2.3-1.12.2.jar)
  ColytraLoadingPlugin (Colytra-Mod-1.12.2.jar)
  NWRTweak (Redstone-Paste-Mod-1.12.1.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 7/3/18 12:19 PM
XRay version: 58
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Modern Metals (modernmetals)
Caused by: java.lang.NoSuchMethodError: com.mcmoddev.lib.util.ConfigBase$Options.fluidEnabled(Ljava/lang/String;Ljava/lang/Boolean;)V
	at com.mcmoddev.modernmetals.util.Config.init(Config.java:82)
	at com.mcmoddev.modernmetals.proxy.CommonProxy.preInit(CommonProxy.java:44)
	at com.mcmoddev.modernmetals.proxy.ClientProxy.preInit(ClientProxy.java:25)
	at com.mcmoddev.modernmetals.ModernMetals.preInit(ModernMetals.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:245)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_162, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 141274256 bytes (134 MB) / 451416064 bytes (430 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2705 59 mods loaded, 59 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version         | Source                                        | Signature                                |
	|:----- |:------------------- |:--------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft           | 1.12.2          | minecraft.jar                                 | None                                     |
	| UCH   | mcp                 | 9.42            | minecraft.jar                                 | None                                     |
	| UCH   | FML                 | 8.0.99.99       | forge-1.12.2-14.23.4.2705.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge               | 14.23.4.2705    | forge-1.12.2-14.23.4.2705.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | bowinfinityfix      | rv5             | minecraft.jar                                 | e250ba31147feb059b86cfd74ee61a8aeb88fb9b |
	| UCH   | obfuscate           | 0.2.3           | minecraft.jar                                 | None                                     |
	| UCH   | jei                 | 4.8.3.126       | jei_1.12.2-4.8.3.126.jar                      | None                                     |
	| UCH   | base                | 3.3.1           | B.A.S.E-Mod-1.12.1.jar                        | None                                     |
	| UCH   | veinminer           | 0.38.2          | VeinMiner-1.12-0.38.2.647+b31535a.jar         | None                                     |
	| UCH   | basemetals          | 2.5.0-beta3     | Base-Metals-Mod-1.12.1.jar                    | None                                     |
	| UCH   | biomesoplenty       | 7.0.1.2325      | BiomesOPlenty-1.12.2-7.0.1.2325-universal.jar | None                                     |
	| UCH   | bookshelf           | 2.3.522         | Bookshelf-1.12.2.jar                          | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | buildhelper         | 1.0.1           | BuildHelper-Mod-1.12.2.jar                    | None                                     |
	| UCH   | chromaticfoliage    | 1.0.2           | Chromatic-Foliage-Mod-1.12.2.jar              | None                                     |
	| UCH   | clumps              | 2.0.0           | Clumps-Mod-1.12.jar                           | None                                     |
	| UCH   | codechickenlib      | 3.1.5.331       | CodeChickenLib-1.12.2.jar                     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | colored_water       | 1.12.2-b34      | ColoredWater-Mod-1.12.2.jar                   | None                                     |
	| UCH   | colytra             | 1.0.4.3         | Colytra-Mod-1.12.2.jar                        | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCH   | creativeplus        | 1.0.2           | Creative-Plus-Mod-1.12.2.jar                  | None                                     |
	| UCH   | ctdcore             | 1.2.2           | CTD-Core-1.12.1.jar                           | 441b509a0f58a0ef41aca8daf1be20d96287635e |
	| UCH   | cucumber            | 1.0.4           | Cucumber-Mod-1.12.2.jar                       | None                                     |
	| UCH   | customspawner       | 3.11.3          | Custom-Mob-Spawner-Mod-1.12.2.jar             | None                                     |
	| UCH   | ferdinandsflowers   | 1.10.1b         | Ferdinands-Flowers-Mod-1.12.2.jar             | None                                     |
	| UCH   | flagged             | 0.1.1           | Flagged-Mod-1.12.2.jar                        | None                                     |
	| UCH   | flatcoloredblocks   | mc1.12-6.6      | Flat-Colored-Blocks-Mod-1.12.1.jar            | None                                     |
	| UCH   | forgivingvoid       | 1.0.17          | Forgiving-Void-Mod-1.12.2.jar                 | None                                     |
	| UCH   | furnaceoverhaul     | 1.0.3           | Furnace-Overhaul-Mod-1.12.2.jar               | None                                     |
	| UCH   | giacomosfoundry     | 1.3.13          | Giacomos-Foundry-Mod-1.12.2.jar               | None                                     |
	| UCH   | gottschcore         | 1.2.0           | GottschCore-1.12.2.jar                        | None                                     |
	| UCH   | huggablecactuses    | 1.1             | Huggable-Cactuses-Mod-1.12.2.jar              | None                                     |
	| UCH   | ism                 | 2.0.0 MC-1.12.2 | Instant-Structures-Mod-1.12.2.jar             | None                                     |
	| UCH   | jarm                | 1.12.2.11       | jarm-1.12.2.11.jar                            | None                                     |
	| UCH   | lobotomy            | 1.12.2          | Lobotomy-Mod-1.12.2.jar                       | None                                     |
	| UCH   | longerdays          | 1.0.4           | Longer-Days-Mod-1.12.2.jar                    | None                                     |
	| UCH   | orespawn            | 3.2.0           | MMD-OreSpawn-Library-1.12.1.jar               | None                                     |
	| UCH   | moglowstone         | 1.4.1           | Mo-Glowstone-Mod-1.12.1.jar                   | 441b509a0f58a0ef41aca8daf1be20d96287635e |
	| UCH   | moarores            | 1.1.1           | Moarores-1.1.1.jar                            | None                                     |
	| UCEE  | modernmetals        | 2.5.0-beta5     | ModernMetals-1.12-2.5.0-beta5.120.jar         | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UC    | cgm                 | 0.1.2           | MrCrayfishs-Guns-Mod-1.12.2.jar               | None                                     |
	| UC    | neat                | 1.4-15          | Neat-Mod-1.12.jar                             | None                                     |
	| UC    | nei                 | 2.4.1           | Not-Enough-Items-1.12.2-Recommended.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | orecanes            | 1.3.0           | Ore-Canes-Mod-1.12.2.jar                      | None                                     |
	| UC    | harvestcraft        | 1.12.2u         | Pam's+HarvestCraft+1.12.2u.jar                | None                                     |
	| UC    | simplerecipes       | 1.12a           | Pams-Simple-Recipes-Mod-1.12.jar              | None                                     |
	| UC    | placebo             | 1.3.4           | Placebo-1.12.2-1.3.4.jar                      | None                                     |
	| UC    | plants2             | 2.8.6           | Plants-1.12.2-2.8.6.jar                       | None                                     |
	| UC    | redstonepaste       | 1.7.5           | Redstone-Paste-Mod-1.12.1.jar                 | None                                     |
	| UC    | reforged            | 0.7.5           | Reforged-Mod-1.12.jar                         | None                                     |
	| UC    | sit                 | v1.0            | Sit-Mod-1.12.2.jar                            | None                                     |
	| UC    | solarfurnace        | 1.0             | SolarFurnace-Mod-1.12.2.jar                   | None                                     |
	| UC    | spartanweaponry     | beta 1.1        | Spartan-Weaponry-Mod-1.12.2.jar               | None                                     |
	| UC    | spikemod            | 1.12-2.1.0      | Spike-Mod-1.12.jar                            | None                                     |
	| UC    | terra               | 1.0             | Terra-Mod-1.12.2.jar                          | None                                     |
	| UC    | thecrystallia       | 0.0.7.1         | The-Crystallia-Mod-1.12.2.jar                 | None                                     |
	| UC    | bspkrscore          | at_0.9          | TreeCapitator-Mod-1.12.jar                    | None                                     |
	| UC    | treecapitator       | at_0.9          | TreeCapitator-Mod-1.12.jar                    | None                                     |
	| UC    | veinminermodsupport | 0.38.2          | VeinMiner-1.12-0.38.2.647+b31535a.jar         | None                                     |
	| UC    | wanionlib           | 1.12.2-1.2      | WanionLib-1.12.2-1.2.jar                      | None                                     |
	| UC    | zeiyocraft          | 0.8.4           | ZeiyoCraft-Mod-1.12.2.jar                     | None                                     |

	Loaded coremods (and transformers): 
BIFLoader (Bow-Infinity-Fix-Mod-1.12.2.jar)
  com.github.parker8283.bif.Transformer
ObfuscatePlugin (obfuscate-0.2.3-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
ColytraLoadingPlugin (Colytra-Mod-1.12.2.jar)
  c4.colytra.core.asm.ElytraTransformer
NWRTweak (Redstone-Paste-Mod-1.12.1.jar)
  net.fybertech.nwr.NWRTransformer
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 10.18.14.4264' Renderer: 'Intel(R) HD Graphics 4200'

**Comment by dshadowwolf** [comment]
You are not using an official release of BaseMetals - or even one of our maven builds. Please come back when you're actually using a version from either our Maven or from Curseforge.

**Comment by dshadowwolf** [comment]
The key is here:
```
| UCH   | basemetals          | 2.5.0-beta3     | Base-Metals-Mod-1.12.1.jar                    | None                                     |
```
You've got an unsigned, third party, unofficial and unsigned build of BaseMetals that is several versions out of date. Try using the official, up-to-date, current version. We do not support third-party builds downloaded from shady sites like 9minecraft of its brethren and all of our builds have been signed for a while now, even the ones on our maven.

**Comment by jriwanek** [comment]
@Tchernobog1 Also, please go read *everything* at this site: <http://stopmodreposts.org/>
