### ISSUE TITLE
Do you have a list of...?

### ISSUE THREAD

**Issue by JadianRadiator** [MinecraftModDevelopmentMods/ModernMetals#110]
Do you have a list of color codes for the materials either in hex or convertible to hex?
I want to add Base Metals and Modern Metals metals as tools in Artisan's Workshop.
Some of them it already has, but I want to add all of the Base/Modern Metals stuff as Artisans Workshop tool material.
Also posted on [Base Metals](https://github.com/MinecraftModDevelopmentMods/BaseMetals/issues/381), as I don't know a central place I could post for both at once.

**Comment by dshadowwolf** [comment]
See response on BaseMetals issue
