### ISSUE TITLE
Request: Support for IE metal armors: Constaintain, Invar

### ISSUE THREAD

**Issue by Divineaspect** [MinecraftModDevelopmentMods/ModernMetals#12]
Constaintain, Invar are both real world alloys with interesting properties. While I realize that they are composed of base metals, I feel they would fit with modern metals in terms of scope.

**Comment by jriwanek** [comment]
Invar should be provided by BaseMetals, The former I'll take a look into. Thanks!

https://en.wikipedia.org/wiki/Constantan (For my notes)

**Comment by jriwanek** [comment]
Constantin is far too similar recipe wise to cupronickel and while I'm aware that they are infact different, I'd rather not add alloying complexity unnecessarily.

**Comment by jriwanek** [comment]
Cupronickel is too similar to constantin by far, it'd break tinkers construct support too.
