### ISSUE TITLE
How to install it?

### ISSUE THREAD

**Issue by Xaos-ua** [MinecraftModDevelopmentMods/ModernMetals#120]
Hi!
Perhaps this is a strange question, but how to install this mod? I tried to do as usual, throwing the archive or folder into the "mods". But, when starting the game, the mod wasn't detected. I really like BaseMetals, and I would like to install this addon (and others as well, because with them the same problem). Probably I just don’t know how to install such modifications. I would appreciate if you help.

**Comment by dshadowwolf** [comment]
jar goes in "mods" - thats it... Did you get it from Curse or from another source ?

**Comment by jriwanek** [comment]
Well, barring that you'll need Forge, and ModernMetals's dependencies. Show game log for any further assistance.
