### ISSUE TITLE
Titanium config missing

### ISSUE THREAD

**Issue by Pengu-Hunter** [MinecraftModDevelopmentMods/ModernMetals#125]
Minecraft version: 1.12.2
Forge version: 14.23.5.2854
Environment: Singleplayer

Mod name: Modern Metals
Mod version: rc2.152

The ore gen config for titanium is missing from the orespawn folder, modermetals config file, titanium ore controls for nether and end metals are present in their respective config file but missing from modern metals, and titanium is also missing from the overworld so its not like the titanium config is invisible but still functional.

Regards Pengu

**Comment by jriwanek** [comment]
Not a bug, By default, Titanium is an alloy, which is made from rutile and magnesium, we do however provide an ore block for it, so people who want it as a worldgen item are expected to add an entry to their json themselves with it, if you're not sure you could copy and change the rutile entry, or completely replace it at your preference.
