### ISSUE TITLE
Achievements typo

### ISSUE THREAD

**Issue by drakray** [MinecraftModDevelopmentMods/ModernMetals#28]
Achievement is named stainnesssteel_maker rather than stainless_steel_maker
Achievement is named galvanizedsteel_maker rather than galvanized_steel_maker
Named wrongly in chat and achievement page

ModernMetal 0.11.0, Forge 2066

**Comment by jriwanek** [comment]
https://github.com/MMDModding/ModernMetals/blob/master/src/main/java/modernmetals/init/Achievements.java

Already fixed in dev.

**Comment by drakray** [comment]
Yeah sorry, I saw that after when I checked to be use it was not BetterAchievement's fault :/ lol

**Comment by jriwanek** [comment]
No problem, better to over report than to under report. so thanks for your time.
