### ISSUE TITLE
[SUGGESTION] Give different materials different strength and durability based on real life properties

### ISSUE THREAD

**Issue by squarles** [MinecraftModDevelopmentMods/ModernMetals#33]
As of both the 1.10.2 version and 1.8.9 backport, tools all seem to have the same damage dealt and durability. Mining speed not tested.

EDIT: maybe also change some textures to match real life color like for tantalum or zirconium, especially because I can't tell some ores (like those two, or titanium) from stone at all

**Comment by squarles** [comment]
UPDATE: I've figured out that the issue with not seeing the ores was actually caused by the dimension setting in MMD OreSpawn being "+" instead of "0" by default, and not generating.

**Comment by jriwanek** [comment]
Materials are more varied in dev
