### ISSUE TITLE
Tinkers Construct Support

### ISSUE THREAD

**Issue by jriwanek** [MinecraftModDevelopmentMods/ModernMetals#5]

**Comment by jriwanek** [comment]
Initial melting support now added.

Still todo: Tools and related.

**Comment by TyoAtrosa** [comment]
also a continuation of my list from the base metals suggestions:

Osmium: usable as a Hammer head, converts a Tinkers hammer from a 3x3 mining area to a single block Crack hammer.

Iridium: as a Hammer head, shrinks mining spread down to 2x2 but greatly increases speed.

Titanium: Lightweight effect like cobalt but lower mining level and durability, uses less hunger when using tool. 

Silicon: allows a tool to be charged with RF, low Durabilty and handle modifier, wood mining level and damage.

**Comment by jriwanek** [comment]
Tools and whatnot implemented

Still todo: traits.

**Comment by jriwanek** [comment]
Moved to central tracker

**Comment by dshadowwolf** [comment]
Adding these to the central TODO

**Comment by dshadowwolf** [comment]
Changing the size of the TiC hammers harvest area is notm currently, possible in a safe manner. TiC has the existing size modifiers hard-coded into the code. The others are still active.

**Comment by YaibaToKen** [comment]
Are the traits mentioned here the ones @jriwanek sent me a gist with?
