### ISSUE TITLE
Works with ic2?

### ISSUE THREAD

**Issue by Niicolaxx** [MinecraftModDevelopmentMods/ModernMetals#64]

**Comment by dshadowwolf** [comment]
That... is being worked on. Without visible source and with the documentation not fully understood, we've halted on full integration until we have the code in a much more stable state. However... it should work with the macerator, at the least.

**Comment by dshadowwolf** [comment]
Recent -dev has implemented more compat with IC2 though the IC2 Forge Hammer remains an issue as the interface for it is consistently null and figuring out how to register the recipes for it is remaining elusive.

**Comment by dshadowwolf** [comment]
BaseMetals -dev now has full integration with the machines we feel worth it and the Forge Hammer -- soon there will be work to make similar progress here

**Comment by jriwanek** [comment]
should be fixed in beta5
