### ISSUE TITLE
[1.12.2] Crash with TIC Integration

### ISSUE THREAD

**Issue by TheLimePixel** [MinecraftModDevelopmentMods/ModernMetals#73]
https://pastebin.com/18wZ4zVw

**Comment by dshadowwolf** [comment]
This... actually looks like a bad mod interaction - I have seen similar before, coming from Extra Utilities 2 and another mod that added their own Tinkers' Traits with generic names - like "radioactive". This is easy enough to fix, I've done it a few times already, just takes munging around with some internal names is all.

Thanks for the report!

**Comment by dshadowwolf** [comment]
Just released -beta2.31 of Base Metals on Curse - it's "under review" - which should resolve this problem. Once you've managed to test, let us know so we can close this bug. (or you can close it yourself, if you so choose)

**Comment by dshadowwolf** [comment]
The -beta3 series has implemented a few changes such that there should be no conflict over trait names or modifier names.

At this time the only crashes that will occur are when multiple mods try to register the same material with Tinkers' and don't check to see if it has already been registered. Closing this issue as "most likely resolved"
