### ISSUE TITLE
[1.12.2] MM (2.5.0-beta5.120) and IC2/TechReborn Irdium problem

### ISSUE THREAD

**Issue by wamc2017** [MinecraftModDevelopmentMods/ModernMetals#97]
Hi,

I updated BaseMetals and ModernMetals today to the latest beta in my private pack, which includes Industrial Craft 2 and Tech Reborn. The game crashes at the start (see error.log below) 
Everything worked fine with BaseMetals version 2.5.0-beta4.145 and ModernMetals version 2.5.0-beta4.91. Also it works fine if set EnableIridium in the config to false in version 2.5.0-beta5.120.
Tried it in a little testpack with only MM, IC2 and Techreborn (and dependencies) installed.

It only happens if TR, IC2 and MM are installed together!

Here is the crashreport: https://pastebin.com/j4X1mHWL
Here is the modlist I used to test the problem: https://pastebin.com/cZN05qWC
Forge version is 14.23.2.2627
Minecraft version is 1.12.2

If I should report this to the techreborn or ic2 guys, I'll do it, but it only happens when I update MM, that's why I reported it here first... :)

Thanks for looking into it.
Best regards
wamc

**Comment by joselitosn** [comment]
Seems like the same as this
https://bt.industrial-craft.net/view.php?id=2347

**Comment by dshadowwolf** [comment]
Fixed in -dev already.

And yes, exactly the issue.
