### ISSUE TITLE
Bug in com.mcmoddev.modernmetals.integration.plugins.TinkersConstruct.registerAlloy

### ISSUE THREAD

**Issue by PixelNectar** [MinecraftModDevelopmentMods/ModernMetals#98]
Line 129 in file com.mcmoddev.modernmetals.integration.plugins.TinkersConstruct.java:
The lambda expression in
`.filter(elem -> !(elem instanceof String))`
should be
`.filter(elem -> (elem instanceof String))`.

As is, this code filters Strings out and leaves integers; Stream.filter is a positive filter (might not be the right word), that is to say that it keeps elements for which the lambda is true instead of removing elements for which the lambda is true.

**Comment by YaibaToKen** [comment]
@dshadowwolf this should be closed as the code in question has already been changed according to the latest commit on this repo
